### ISSUE TITLE
Review API calls for migrating text parsing from the front-end to the back-end.

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/louis-frontend#12]
1. makeApiRequest:

        - This function is responsible for making an API request to retrieve a response for a given question.
        - It updates the state variables and handles errors based on the API response.
        - The function takes a question as an argument and stores it as the last asked question using the lastQuestionRef reference.
        - It resets the error state and sets the loading state to true.
        - Inside a try-catch-finally block, it sends a chat request to the chatApi function.
        - The chat request includes the chat history, approach, and overrides.
        - The response from the chatApi is added to the answers array in the state.
        - If an error occurs during the API request, it sets the error state with an error message.
        - Finally, it sets the loading state to false.

2. chatApi:
        
        - This function is an asynchronous function that sends a POST request to the "/chat" endpoint.
        - It takes an options object containing the chat history, approach, and overrides.
        - The function uses the fetch API to send the POST request with the specified headers and request body.
        - The request body includes the chat history, approach, and overrides.
        - The function expects a JSON response from the API.
        - If the response status is not in the 200-299 range or the response is not okay, it throws an error with the parsed response         error message.
        - Otherwise, it returns the parsed response as an AskResponse object.

3. Request Body Overrides:

       - 'promptTemplate': A template used to format the prompt for generating responses.
       - 'excludeCategory': A category to exclude from the response generation. It can be used to filter out certain types of responses based on categories.
       - 'top': The count of responses to retrieve.
       - 'semanticRanker': A flag indicating whether to use a semantic ranker to improve the quality of responses.
       - 'semanticCaptions': A flag indicating whether to use semantic captions for generated responses.
       - 'suggestFollowupQuestions': A flag indicating whether to suggest follow-up questions in the generated response.

4. Approaches Enum:

       - The Approaches enum has been defined with three different approaches: RetrieveThenRead, ReadRetrieveRead, and ReadDecomposeAsk.
       - This enum is used to specify the approach in the AskRequest and ChatRequest objects.

5. AskRequest and ChatRequest:

       - The AskRequest type has been updated to include the question property, which represents the user's question.
       - The AskRequest and ChatRequest types now include the approach property, which should be one of the enum values from Approaches.
       - The AskRequest and ChatRequest types now have an optional overrides property of type AskRequestOverrides. These overrides allow customization of the request parameters.

6. AskRequestOverrides:

       - The AskRequestOverrides type has been defined to include various request overrides that can be passed to the API.
       - It includes properties such as semanticRanker, semanticCaptions, excludeCategory, top, temperature, promptTemplate, promptTemplatePrefix, promptTemplateSuffix, and suggestFollowupQuestions.
       - These properties allow fine-tuning the behavior of the response generation process.

7. AskResponse:

       - The AskResponse type has been updated to include additional properties:
       - thoughts: A string or null representing any additional thoughts related to the answer.
       - data_points: An array of strings representing relevant data points associated with the answer.
       - error: An optional string indicating any error that occurred during the API response.

**Comment by rngadam** [comment]
Add the work you've done so far to a DEVELOPER.md file and create pull request.

Update to focus on an example of JSON response and how it maps to the frontend.
